language: ruby

rvm:
  - 4.0
  - ruby-head

env:
  - "RAILS_VERSION=7.0.0"
  - "RAILS_VERSION=7.1.0"
  - "RAILS_VERSION=8.0.0"
  - "RAILS_VERSION=main"

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=main"
